### PR TITLE
implement dropdowns for version control and versioning scheme

### LINKED ISSUE #7: Make version control question a dropdown table
Options should be
- Git
- Svn
- Mercurial
- Other -> explanation field

### PR DESCRIPTION
**Pull request by OleMussmann**
Implement dropdowns for version control and versioning scheme. Update DOCX template to catch those changes.

Closes #7

### CODE REVIEW

**Comment by sjvrijn** [comment]
The two dropdowns currently say "Select...". Do we want to set these to default to SemVer and Git respectively instead?

**Comment by sjvrijn** [comment]
As another suggestion: I think I would prefer spelling out 'Semantic Versioning' and 'Calendar Versioning', since I don't think we should expect our target audience to know these terms.

**Review by OleMussmann — COMMENTED** [review]
"Select" seems ok to me.

Writing out semver and calver looks like a good idea.

**Comment by sjvrijn** [comment]
Semver/Calver are now written out.
We can always set a default later depending on what we decide more specifically about the target audience.

**Review by OleMussmann — COMMENTED** [review]
lgtm, but I can't approve it, only comment. Why, GitHub?!

**Review by sjvrijn — APPROVED** [review]
Looks good to us 😉

**Pull request merged**
